server:
  port: 0

spring:
  profiles:
    active: db
  application:
    name: user-service
  datasource:
    url: ${url}
    username: ${username_}
    password: ${password_}
    driver-class-name: ${driver-class-name}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true #??? ??? ????
    fetch-registry: true #??? ???? ?? ?? ??? ??
    service-url:
      defaultZone: http://192.168.0.138:8761/eureka # ??? ??? ??


#MySQL ????