server:
  port: 8000
spring:
  application:
    name: apigateway-server
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            message: Global Filter Default Message Test
            pre: true
            post: true
      routes: #개별 마이크로 서비스 정보를 route에 기입함
        - id: first-service
          uri: http://localhost:8001/
          predicates:
            - Path=/first-service/**   #여기로 들어오면 uri 로 보내주겠다
          filters:
#            - AddRequestHeader=fsregh,fsreqhvyml   #first-request-header-yml
#            - AddResponseHeader=fsreshyml,fsreshvyml  #first-response-header-yml
            - CustomFilter

        - id: second-service
          uri: http://localhost:8002/
          predicates:
            - Path=/second-service/**   #여기로 들어오면 uri 로 보내주겠다

# 호출 우선순위 글로벌 pre > 커스텀 pre > 커스텀 post > 글로벌 post